### ISSUE TITLE
support org.springframework.scheduling.annotation.Scheduled annotation as an entry

### ISSUE THREAD

**Issue by lidaobing** [xbeeant/spring-java-idea-plugin#12]
as the attached image

<img width="940" alt="image" src="https://user-images.githubusercontent.com/27529/219574791-e50dec9f-3633-4791-8bfb-e5222b4dd233.png">

and the spring plugin of vscode support list Scheduled entries: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-spring-boot-dashboard
<img width="283" alt="image" src="https://user-images.githubusercontent.com/27529/219575514-a6a411f3-8a20-4289-9230-9a3b8c9a039f.png">

**Comment by beeant0512** [comment]
please upgrade to version 1.0.17

**Comment by lidaobing** [comment]
@beeant0512 when will 1.0.17 be released?

**Comment by beeant0512** [comment]
> @beeant0512 when will 1.0.17 be released?

it has already released to Jetbrains plugins marketplace 

https://plugins.jetbrains.com/plugin/14239-spring--java-tools/versions

**Comment by lidaobing** [comment]
@beeant0512 found it, thank you.
