### ISSUE TITLE
For encapsulated RequestMapping

### ISSUE THREAD

**Issue by 1036795720** [xbeeant/spring-java-idea-plugin#15]
Encapsulated RequestMapping cannot be displayed in the request list
![mmexport1680232113896](https://user-images.githubusercontent.com/64831145/229013071-debfbf48-e567-4bf0-8b59-e24ac4c3f3a3.png)
![mmexport1680232065096](https://user-images.githubusercontent.com/64831145/229013082-a7611642-2835-45d8-acdd-d928faa100c9.png)

**Comment by beeant0512** [comment]
@1036795720 can u provide some code example？
