### ISSUE TITLE
希望支持IDEA 2024版本

### ISSUE THREAD

**Issue by ccpwcn** [xbeeant/spring-java-idea-plugin#16]
现在JetBrains的IDEA 2024出来了，但是官网插件市场提示：
![image](https://github.com/xbeeant/spring-java-idea-plugin/assets/5465756/e02d9910-83eb-48b6-80ca-8080f5083b2d)
抽空更新一下吧。

**Comment by beeant0512** [comment]
已经推送新版本到官方插件市场
