### ISSUE TITLE
生成serialVersionUID

### ISSUE THREAD

**Issue by ccpwcn** [xbeeant/spring-java-idea-plugin#3]
看介绍还可以为Java类生成serialVersionUID这个字段，可是我找了半天也没找到这个怎么操作，请指教一下啊。

**Comment by ccpwcn** [comment]
已经找到了怎么搞了，谢谢。

**Comment by JabinHao** [comment]
怎么生成呀

**Comment by ccpwcn** [comment]
> 怎么生成呀

在类内部，按ALT+INSERT键，点击serilize me
